#!/usr/bin/env bash
# Install the OPERATOR-OWNED authority check OUTSIDE the agent-writable
# workspace, then write the gate config that points at it.
#
# Run by reset-demo.sh (and safe to re-run). It never overwrites an existing
# live authority.json, so a presenter's freeze/thaw state survives a re-run;
# reset-demo.sh forces it back to 'active' explicitly.
set -euo pipefail
source "$(dirname "$0")/_env.sh"

mkdir -p "$AUTHORITY_HOME"
cp "$REPO_ROOT/operator/check-beneficiary.mjs" "$AUTHORITY_HOME/check-beneficiary.mjs"
if [ ! -f "$AUTHORITY_HOME/authority.json" ]; then
  cp "$REPO_ROOT/operator/authority.json" "$AUTHORITY_HOME/authority.json"
fi

cat > "$REPO_ROOT/.rigorix/preconditions.toml" <<EOF
# GENERATED by .rigorix/scripts/setup-authority.sh — do not edit by hand.
#
# The gate runs this check at DISPATCH time: after the human approval, right
# before the step would execute. The check binary and the authority file live
# OUTSIDE the repository ($AUTHORITY_HOME), so an agent with write access to
# this repo cannot forge the authority it is checked against.
#
# ADR-017 dispatch-time precondition:
#   match          = the payout step's command
#   require_params = the gate fails closed if /command is missing
#   command        = argv-only, resolved outside the workspace
#   failure        = deny (a non-zero exit refuses the step)

[[preconditions]]
id = "beneficiary-authorized"
match = { tool = "run_command", params = [{ pointer = "/command", kind = "glob", value = "*execute_payout.sh*" }] }
require_params = ["/command"]
command = ["node", "$AUTHORITY_HOME/check-beneficiary.mjs"]
timeout_ms = 5000
failure = "deny"
EOF

echo "installed authority check -> $AUTHORITY_HOME"
echo "wrote .rigorix/preconditions.toml (gate armed, check outside the repo)"
