#!/usr/bin/env bash
# Install the OPERATOR-OWNED authority check OUTSIDE the agent-writable
# workspace, then write the gate config that points at it.
#
#   setup-authority.sh              default: per-user $HOME install (today)
#   setup-authority.sh --isolated   OS boundary: root-owned, non-writable
#
# Default mode is unchanged: the check/authority live under
#   $HOME/.rigorix-authority-demo
# and the boundary is path containment + the PreToolUse hook (not a sandbox).
#
# Isolated mode installs them under
#   /usr/local/lib/rigorix-authority-demo   (override: RIGORIX_ISOLATED_HOME)
# root-owned, check 0555 / authority 0444, so the agent's UID cannot write them.
# It refuses to proceed when the invoking user has passwordless sudo (that would
# defeat the boundary); set RIGORIX_ALLOW_PASSWORDLESS_SUDO=1 to downgrade to a
# loud warning.
#
# Both configs declare `authority_path` (ADR-017 #987): the engine hashes that
# artifact at dispatch and records `authority_digest` in the signed finding, so
# a changed authority is visible in the record. `require_immutable_check` is
# left at its default (false), so the boundary assessment is recorded
# (`check_writable`) but never refuses — the default flow is unchanged.
#
# Run by reset-demo.sh (and safe to re-run). It never overwrites an existing
# live authority.json, so a presenter's freeze/thaw state survives a re-run;
# reset-demo.sh forces it back to 'active' explicitly.
set -euo pipefail
source "$(dirname "$0")/_env.sh"

ISOLATED_HOME="${RIGORIX_ISOLATED_HOME:-/usr/local/lib/rigorix-authority-demo}"

# Default-mode gate config — byte-for-byte the pre-isolation output, plus the
# `authority_path` attribution declaration.
write_gate_config_default() {
  cat > "$REPO_ROOT/.rigorix/preconditions.toml" <<EOF
# GENERATED by .rigorix/scripts/setup-authority.sh — do not edit by hand.
#
# The gate runs this check at DISPATCH time: after the human approval, right
# before the step would execute. The check binary and the authority file live
# OUTSIDE the repository ($AUTHORITY_HOME), so an agent with write access to
# this repo cannot forge the authority it is checked against.
#
# ADR-017 dispatch-time precondition:
#   match          = the payout step's command
#   require_params = the gate fails closed if /command is missing
#   command        = argv-only, resolved outside the workspace
#   failure        = deny (a non-zero exit refuses the step)
#   authority_path = the artifact the check consults; the engine records its
#                    sha256 (`authority_digest`) in the signed finding (#987).
#                    Attribution only — a changed authority becomes visible.

[[preconditions]]
id = "beneficiary-authorized"
match = { tool = "run_command", params = [{ pointer = "/command", kind = "glob", value = "*execute_payout.sh*" }] }
require_params = ["/command"]
command = ["node", "$AUTHORITY_HOME/check-beneficiary.mjs"]
timeout_ms = 5000
failure = "deny"
authority_path = "$AUTHORITY_HOME/authority.json"
EOF
}

# Isolated-mode gate config — same gate, OS-enforced boundary.
write_gate_config_isolated() {
  cat > "$REPO_ROOT/.rigorix/preconditions.toml" <<EOF
# GENERATED by .rigorix/scripts/setup-authority.sh --isolated — do not edit by hand.
#
# The gate runs this check at DISPATCH time: after the human approval, right
# before the step would execute. In isolated mode the check and the authority
# are root-owned OUTSIDE the repository ($AUTHORITY_HOME, 0555/0444), so the
# agent's UID cannot write them — an OS boundary, not only path containment.
# Precondition: the agent user must not have passwordless sudo.
#
# ADR-017 dispatch-time precondition:
#   match          = the payout step's command
#   require_params = the gate fails closed if /command is missing
#   command        = argv-only, resolved outside the workspace
#   failure        = deny (a non-zero exit refuses the step)
#   authority_path = the artifact the check consults; the engine records its
#                    sha256 (`authority_digest`) in the signed finding (#987).

[[preconditions]]
id = "beneficiary-authorized"
match = { tool = "run_command", params = [{ pointer = "/command", kind = "glob", value = "*execute_payout.sh*" }] }
require_params = ["/command"]
command = ["node", "$AUTHORITY_HOME/check-beneficiary.mjs"]
timeout_ms = 5000
failure = "deny"
authority_path = "$AUTHORITY_HOME/authority.json"
EOF
}

setup_default() {
  # A prior isolated run leaves a marker; drop it before resolving the path.
  export AUTHORITY_HOME="${RIGORIX_DEFAULT_AUTHORITY_HOME:-$HOME/.rigorix-authority-demo}"
  rm -f "$AUTHORITY_MARKER"

  mkdir -p "$AUTHORITY_HOME"
  cp "$REPO_ROOT/operator/check-beneficiary.mjs" "$AUTHORITY_HOME/check-beneficiary.mjs"
  if [ ! -f "$AUTHORITY_HOME/authority.json" ]; then
    cp "$REPO_ROOT/operator/authority.json" "$AUTHORITY_HOME/authority.json"
  fi

  write_gate_config_default
  echo "installed authority check -> $AUTHORITY_HOME"
  echo "wrote .rigorix/preconditions.toml (gate armed, check outside the repo)"
}

setup_isolated() {
  # Fail closed if the agent user can sudo without a password: root ownership
  # protects nothing then.
  if sudo -n true 2>/dev/null; then
    if [ "${RIGORIX_ALLOW_PASSWORDLESS_SUDO:-0}" = "1" ]; then
      echo "WARNING: passwordless sudo is available for '$(id -un)'; the agent user" >&2
      echo "         could sudo the authority write — the isolation claim does NOT hold." >&2
      echo "         (RIGORIX_ALLOW_PASSWORDLESS_SUDO=1: continuing with a warning)" >&2
    else
      echo "error: passwordless sudo is available for '$(id -un)'." >&2
      echo "       An isolated (root-owned) authority protects nothing when the agent" >&2
      echo "       user can sudo. Remove the NOPASSWD rule, or set" >&2
      echo "       RIGORIX_ALLOW_PASSWORDLESS_SUDO=1 to continue with a warning." >&2
      exit 1
    fi
  fi

  local root_group
  root_group="$(id -gn root 2>/dev/null || echo root)"

  sudo mkdir -p "$ISOLATED_HOME"
  sudo chown root:"$root_group" "$ISOLATED_HOME"
  sudo chmod 0755 "$ISOLATED_HOME"
  sudo install -m 0555 -o root -g "$root_group" \
    "$REPO_ROOT/operator/check-beneficiary.mjs" "$ISOLATED_HOME/check-beneficiary.mjs"
  if [ ! -f "$ISOLATED_HOME/authority.json" ]; then
    sudo install -m 0444 -o root -g "$root_group" \
      "$REPO_ROOT/operator/authority.json" "$ISOLATED_HOME/authority.json"
  fi

  printf '%s\n' "$ISOLATED_HOME" > "$AUTHORITY_MARKER"
  export AUTHORITY_HOME="$ISOLATED_HOME"
  write_gate_config_isolated

  echo "installed authority check -> $ISOLATED_HOME (root:$root_group)"
  echo "  check-beneficiary.mjs  0555"
  echo "  authority.json         0444"
  echo "wrote .rigorix/preconditions.toml (gate armed, OS boundary)"
  echo
  echo "verify the boundary as this user: bash .rigorix/scripts/verify-isolation.sh"
}

case "${1:-}" in
  --isolated) setup_isolated ;;
  "" ) setup_default ;;
  -h|--help)
    sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
    ;;
  *)
    echo "unknown argument: $1 (expected --isolated or nothing)" >&2
    exit 2
    ;;
esac
